/**
 * blackboard.ts
 *
 * The shared project blackboard: a single Markdown file (ORCHATERM_BOARD.md at
 * the workspace root) that the orchestrator rewrites after every plan state
 * change and every dispatched agent is told to read first. Instead of relying
 * solely on pairwise relay briefs (A tells B what it needs to know), all
 * agents coordinate through one inspectable, always-current artifact — the
 * user can open it in their editor and watch the team's state live.
 */

import { invoke } from '@tauri-apps/api/core';
import { OrchestratorPlan, OrchestratorTask } from '../types';

export const BLACKBOARD_FILENAME = 'ORCHATERM_BOARD.md';

/** Instruction appended to dispatch prompts when the board is active. */
export const BLACKBOARD_AGENT_INSTRUCTION =
  'Before starting, read ORCHATERM_BOARD.md in the repository root — it holds the live status of every agent on this project, including results from tasks already completed.';

const STATUS_LABEL: Record<OrchestratorTask['status'], string> = {
  pending: '⏳ Pending',
  running: '▶ Running',
  done: '✅ Done',
  failed: '❌ Failed',
};

function taskSection(task: OrchestratorTask): string {
  const lines = [
    `### ${STATUS_LABEL[task.status]} — ${task.title}`,
    '',
    `Agent: ${task.assignedSessionTitle}`,
  ];

  if (task.dependsOn.length > 0) {
    lines.push(`Depends on: ${task.dependsOn.join(', ')}`);
  }

  if (task.output) {
    lines.push('', `Summary: ${task.output.summary}`);
    const files = task.output.filesModified;
    if (files.length > 0) lines.push(`Files modified: ${files.join(', ')}`);
    if (task.output.needs && task.output.needs.toLowerCase() !== 'none') {
      lines.push(`Handoff to next agent: ${task.output.needs}`);
    }
  }

  return lines.join('\n');
}

/**
 * Renders the board content for a plan. Pure function — deterministic from the
 * plan state so the engine can skip rewriting when nothing changed.
 */
export function buildBlackboardMd(plan: OrchestratorPlan): string {
  const updated = new Date().toISOString().replace('T', ' ').slice(0, 19);

  const sections = [
    `# OrchaTerm Project Board`,
    '',
    `> Auto-generated by OrchaTerm after every task change — do not edit manually.`,
    `> Last updated: ${updated} UTC`,
    '',
    `## Goal`,
    '',
    plan.goal,
    '',
    `## Tasks`,
    '',
    ...plan.tasks.map(taskSection),
    '',
  ];

  return sections.join('\n');
}

/** Full path of the board file inside a workspace. */
export function blackboardPath(workspacePath: string): string {
  // Normalize separators so the path works with the Rust backend on Windows.
  const base = workspacePath.replace(/[\\/]+$/, '').replace(/\\/g, '/');
  return `${base}/${BLACKBOARD_FILENAME}`;
}

/**
 * Writes the board for a plan. Rejects on failure so callers decide how to
 * surface the error (the engine logs it — a board write failure must not be
 * silently ignored, since agents would be reading a stale board).
 */
export async function writeBlackboard(
  plan: OrchestratorPlan,
  workspacePath: string
): Promise<string> {
  const path = blackboardPath(workspacePath);
  await invoke('write_file_path', { path, content: buildBlackboardMd(plan) });
  return path;
}
